name: CI/CD for FastAPI with SQLite in Azure Container

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: noaliraz.azurecr.io 
          username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t noaliraz.azurecr.io/analytics-server:latest .
          docker tag noaliraz.azurecr.io/analytics-server:latest noaliraz.azurecr.io/analytics-server:latest

      - name: Push Docker image
        run: |
          docker push noaliraz.azurecr.io/analytics-server:latest

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'NoaLirazApp'  
          images: 'noaliraz.azurecr.io/analytics-server:latest'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
